{% set python_min = "3.9.0" %}
{% set name = "langgraph" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langgraph-{{ version }}.tar.gz
  sha256: 8a920c05aab6d1d2415078b9619d6c81f663a7619bcc4232b9715f9b877072f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - pydantic >=2.7.4
    - python-xxhash >=3.5.0
    - langgraph-prebuilt >=0.6.0,<0.7.0
    - langgraph-sdk >=0.2.0,<0.3.0
    - langgraph-checkpoint >=2.1.0,<3.0.0
    - python >={{ python_min }},<4.0
    - langchain-core >=0.1

test:
  imports:
    - langgraph
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.github.com/langchain-ai/langgraph
  summary: langgraph
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
