{% set python_min = "3.9.0" %}
{% set name = "langgraph" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langgraph-{{ version }}.tar.gz
  sha256: ab8f6b7b9c50fd2ae35a2efb072fbbfe79500dfc18071ac4ba6f5de5fa181931

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - pydantic >=2.7.4
    - python-xxhash >=3.5.0
    - langgraph-prebuilt >=0.5.0,<0.6.0
    - langgraph-sdk >=0.1.42,<0.2.0
    - langgraph-checkpoint >=2.1.0,<3.0.0
    - python >={{ python_min }},<4.0
    - langchain-core >=0.1

test:
  imports:
    - langgraph
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.github.com/langchain-ai/langgraph
  summary: langgraph
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
