{% set python_min = "3.9.0" %}
{% set name = "langgraph" %}
{% set version = "0.4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langgraph-{{ version }}.tar.gz
  sha256: 391dadf5051bab212d711da62b10ae6c97bbc912a9f812b4b27e92a934a401c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - pydantic >=2.7.4
    - python-xxhash >=3.5.0
    - langgraph-prebuilt >=0.2.0
    - langgraph-sdk >=0.1.42
    - langgraph-checkpoint >=2.0.26
    - python >={{ python_min }},<4.0
    - langchain-core >=0.1

test:
  imports:
    - langgraph
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.github.com/langchain-ai/langgraph
  summary: langgraph
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
